name: angrauasr
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+19

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_typeahead: ^5.2.0
  syncfusion_flutter_pdfviewer: 31.1.19
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  dio: ^5.5.0
  url_launcher: ^6.2.5
  archive: ^3.4.10
  share_plus: ^10.0.2
  http: ^1.2.0
  shared_preferences: ^2.2.2
  open_filex: ^4.4.0


  # Localization support
  flutter_localization: ^0.3.3
  rename: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  rename: ^3.0.2
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/splash/splash.jpg
    




flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/angrauicon.jpg"
  min_sdk_android: 21
